<div id="edit_page" class="dialog">
	<p id="page_error" class="red fleft"></p>&nbsp;<p id="page_success" class="green fleft"></p>
	<div class="clearfix"></div>
	<form id="edit_page_form">
		<input type="hidden" id="page_id" value="0" />
		<div class="form_field">
			<label for="page_url">URL:&nbsp;&nbsp;</label> <input type="text" id="page_url" />   
		</div>
		<div class="form_field">
			<label for="page_title">Заголовок:&nbsp;&nbsp;</label> <input type="text" id="page_title" />   
		</div>
		<div class="form_field">
			<label for="page_keywords">Ключевые слова (keywords):&nbsp;&nbsp;</label> <input type="text" id="page_keywords" />   
		</div>
		<div class="form_field">
			<label for="page_description">Описание (description):&nbsp;&nbsp;</label> <input type="text" id="page_description" />   
		</div>    
		<div class="form_field">
			<textarea class="ckeditor" name="page_content" id="page_content"></textarea>
		</div>
	</form>
</div>