<div id="edit_email" class="dialog">
	<p id="email_error" class="red fleft"></p>&nbsp;<p id="email_success" class="green fleft"></p>
	<div class="clearfix"></div>
	<form id="edit_email_form">
		<input type="hidden" id="email_id" value="0" />
		<div class="form_field">
			<label for="email">E-mail:&nbsp;&nbsp;</label> <input type="text" id="email" />   
		</div>
		<div class="form_field">
			<label for="page_description">Комментарий:&nbsp;&nbsp;</label> <input type="text" id="email_description" />   
		</div>    		
	</form>
</div>