<div id="edit_menu" class="dialog">
	<p id="menu_error" class="red fleft"></p>&nbsp;<p id="menu_success" class="green fleft"></p>
	<div class="clearfix"></div>
	<div class="fright">
			<div id="image_preview"><img src="images/no_photo.png" /></div>			
		</div>
	<form id="edit_menu_form">
		<input type="hidden" id="menu_id" value="0" />
		<div class="form_field">
			<label for="menu_name">Название:&nbsp;&nbsp;</label> <input type="text" id="menu_name" />   
		</div>
		<div class="form_field">
			<label for="menu_order">Порядок:&nbsp;&nbsp;</label> <input type="text" id="menu_order" />   
		</div>
		<div class="form_field">
			<label for="menu_parent_id">Родитель:&nbsp;&nbsp;</label> <select id="menu_parent_id"></select>
		</div>		
		<div class="form_field">
			<label for="menu_page_id">Страница <a rel="0" id="edit_page_link" class="blue edit_page" href="#">(ред.)</a>:&nbsp;&nbsp;</label> <select id="menu_page_id"></select>   
		</div>		
		<div class="form_field">
			<label for="menu_category_id">Категория:&nbsp;&nbsp;</label> 
			<select id="menu_category_id">
				<option value="0">Спрятать</option>
				<option value="1">Верхнее меню</option>
				<option value="2">Меню слева</option>
			</select>
		</div>
		<div class="form_field fleft">
			<label for="image">Изображение:&nbsp;&nbsp;</label> <select id="image"></select>
		</div>
		<div class="form_field fleft">
			<label for="clients">Лого клиентов:&nbsp;&nbsp;</label> <select id="clients"></select>
		</div>		
	</form>	
</div>