<html>
<!--<![endif]-->
<head>
    <meta charset="utf-8" /> 
    <title><?php echo $config['general_title'] ?></title>
    <link href="css/styles.css" type="text/css" rel="stylesheet" />
    <link media="all" type="text/css" href="css/jquery-ui.css" rel="stylesheet">

    <script type="text/javascript" src="/js/lib/jquery.min.js"></script>
    <script type="text/javascript" src="/js/lib/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js/lib/ckeditor/ckeditor.js"></script>    
</head>
<body>
<div class="container">

<!-- Header -->
	<div class="header"><img id="admin_logo" src="images/admin_logo.png" /> Панель администратора</div>