<?php include 'html/header.phtml'; ?>
	
<div id="tabs">
	<ul>
		<li><a href="#tabs-menu">Меню</a></li>
		<li><a href="#tabs-pages">Страницы</a></li>
		<li><a href="#tabs-emails">Подписка на новости</a></li>
		<li><a href="#tabs-settings">Настройки</a></li>		
	</ul>
	<div id="tabs-menu">
		<?php include 'html/tabs/menu_list.phtml'; ?>		
	</div>	
	<div id="tabs-pages">
        <?php include 'html/tabs/pages_list.phtml'; ?>	
	</div>
	<div id="tabs-emails">
		<?php include 'html/tabs/emails_list.phtml'; ?>		
	</div>
	<div id="tabs-settings">
		<?php include 'html/tabs/settings_list.phtml'; ?>			
	</div>
</div>

<?php include 'html/popups/edit_menu.phtml'; ?>
<?php include 'html/popups/edit_page.phtml'; ?>
<?php include 'html/popups/edit_email.phtml'; ?>
<?php include 'html/footer.phtml'; ?>
<script src="js/admin_functions.js" type="text/javascript"></script>