<table class="visibility-table">
	<tr>
		<th width="200">&nbsp;</th>
		<?php foreach($menu as $menu_item) { ?>
			<th><div><?php echo $objCommon->convertString($menu_item['data']->name) ?></div></th>			
		<?php } ?>		
	</tr>
	<tr>
		<th width="200">&nbsp;</th>
		<?php foreach($menu as $menu_item) { ?>
			<th><div><?php echo $objCommon->convertString($menu_item['data']->menu_category_id) ?></div></th>			
		<?php } ?>		
	</tr>
	<tr>
		<td colspan="<?php echo count($news)+1 ?>"><b>Новости</b></td>
	</tr>
	<?php foreach($news as $news_item) { ?>
	<tr>
		<td width="200"><?php echo $objCommon->convertString($news_item->title) ?></td>
		<?php foreach($menu as $menu_item) { ?>
			<td class="settings"><input type="checkbox" value="" /></td>		
		<?php } ?>
	</tr>
	<?php } ?>
	<tr>
		<td colspan="<?php echo count($articles)+1 ?>"><b>К прочтению</b></td>
	</tr>
	<?php foreach($articles as $news_item) { ?>
	<tr>
		<td width="200"><?php echo $objCommon->convertString($news_item->title) ?></td>
		<?php foreach($menu as $menu_item) { ?>
			<td class="settings"><input type="checkbox" value="" /></td>		
		<?php } ?>
	</tr>
	<?php } ?>
</table>