<h2>К&nbsp;прочтению<span>...............................</span></h2>
<div class="articles">
	<p class="black"><a href="" class="black">Дизайн шкафа-купе</a></p>
	<p class="grey">Кабинет руководителя "Верона" - удачное решение для тех, кто хотел бы получить добротный...<span class="blue">»</span></p>
	
	<p class="black"><a href="" class="black">Дизайн шкафа-купе</a></p>
	<p class="grey">Кабинет руководителя "Верона" - удачное решение для тех, кто хотел бы получить добротный...<span class="blue">»</span></p>
	
	<p class="black"><a href="" class="black">Дизайн шкафа-купе</a></p>
	<p class="grey">Кабинет руководителя "Верона" - удачное решение для тех, кто хотел бы получить добротный...<span class="blue">»</span></p>
	
	<div class="clearfix"></div>	
	<button class="blue fright" onclick="location.href='<?php echo $config['articles_all_url'] ?>';"><?php echo $config['articles_button_label'] ?><span>+</span></button>
	<div class="clearfix"></div>
</div>

<div class="hr"></div>


