<h2>К&nbsp;прочтению<span>...............................</span></h2>
<div class="articles">
	<?php foreach($articles as $item) { ?>
		<p class="black"><a href="<?php echo $objCommon->convertString($item->url) ?>" class="black"><?php echo $objCommon->convertString($item->title)?></a></p>
		<p class="grey"><?php echo $objCommon->convertString($item->page_description) ?>...<span class="blue">»</span></p>		
	<?php } ?>
		
	<div class="clearfix"></div>	
	<button class="blue fright" onclick="location.href='<?php echo $config['articles_all_url'] ?>';"><?php echo $config['articles_button_label'] ?><span>+</span></button>
	<div class="clearfix"></div>
</div>

<div class="hr"></div>


