<div class="fleft copyright">
	<div class="grey">Копирайт &copy; <?php echo date("Y") ?>. Все права защищены</div>
	<img src="../images/li.png" />
</div>

<div class="fleft">
	<img src="../images/kh.png" class="tel" />
</div>

<div class="fleft map">
	<img src="../images/map.png" />
</div>

<div class="fleft address">	
	<div class="grey"><?php echo $config['general_company_name'] ?></div>
	<div class="grey"><?php echo $config['general_company_address'] ?></div>
	<div class="grey"><a href="contacts" class="grey">Схема проезда</a></div>
</div>
