<html>
<head>
    <meta charset="utf-8" />
	<meta name="title" content="<?= $title ?>" /> 
	<meta name="keywords" content="<?= $keywords ?>" />
	<meta name="description" content="<?= $description ?>" />
 
    <title><?= $title ?></title>
    <link href="../css/custom_styles.css" type="text/css" rel="stylesheet" />
    
    <script type="text/javascript" src="../js/lib/jquery.min.js"></script>
	<script type="text/javascript" src="../js/lib/jquery.placeholder.min.js"></script>
	<script type="text/javascript" src="../js/lib/bxSlider/jquery.bxSlider.min.js"></script>
	<script type="text/javascript" src="../js/functions.js"></script>	
</head>
<body>
<div class="container">
	<div class="header_top_blocks bg_grey"></div><div class="header_top_blocks bg_blue"></div><div class="header_top_blocks bg_green"></div>
	<div class="clearfix"></div>
	
	<a href=""><img src="../images/logo.png" class="logo" /></a>
	<img src="../images/kh.png" class="tel" />
	
	<div id="header_top_menu" class="fright"><?php include('html/top_menu.phtml') ?></div>	
	<div class="clearfix"></div>
		
	<div class="header" id="header_menu"><?php include('html/main_menu.phtml') ?></div>
	<div class="clearfix"></div>
	
	<div class="col_left fleft">
		<div id="left_menu"><?php include('html/left_menu.phtml') ?></div>
		<div id="news"><?php include('html/news.phtml') ?></div>
		<div id="subscribe"><?php include('html/subscribe.phtml') ?></div>		
		<div id="articles"><?php include('html/articles.phtml') ?></div>		
		<div id="geogr"><?php include('html/geogr.phtml') ?></div>
		
		<a href="" class="fleft mr10"><img src="../images/facebook.png" /></a><a href="" class="fleft mr10"><img src="../images/twitter.png" /></a>
		<br/><img src="../images/clear.gif" height="20" width="1" />
	</div>
	<div class="separator fleft"><img src="../images/clear.gif" height="500" width="5" /></div>
	<div class="col_middle fleft">	
		<?php
			switch($content) { 
				case '[ALL_NEWS]':
					include('html/all_news.phtml');
					break;
				default:
					echo $content;
					break;
			}
		?>
	</div>
	<div class="separator fleft"><img src="../images/clear.gif" height="500" width="5" /></div>
	<div class="col_right fleft">
		<div id="right_menu"><?php include('html/right_menu.phtml') ?></div>
		<div id="recommendations"><?php include('html/recommendations.phtml') ?></div>		
	</div>
	<div class="clearfix"></div>
	
	<div id="footer"><?php include('html/footer.phtml') ?></div>
	<div class="clearfix"></div>
	<div class="header_top_blocks bg_grey"></div><div class="header_top_blocks bg_blue"></div><div class="header_top_blocks bg_green"></div>
</div>
</body>
</html>