<h2>Новости<span>.......................................</span></h2>
<div class="news">
	<p class="grey">17 августа 2011 года</p>
	<p class="black"><a href="" class="black">Кабинет руководителя "Верона" - удачное решение для тех...</a><span class="blue">»</span></p>
	
	<p class="grey">17 августа 2011 года</p>
	<p class="black"><a href="" class="black">Кабинет руководителя "Верона" - удачное решение для тех...</a><span class="blue">»</span></p>
	
	<div class="clearfix"></div>	
	<button class="green fleft" id="subscribe_btn">Подписаться</button>
	<button class="blue fright" onclick="location.href='<?php echo $config['news_all_url'] ?>';"><?php echo $config['news_button_label'] ?><span>+</span></button>
	<div class="clearfix"></div>
</div>

<div class="hr"></div>