<h2>Новости<span>.......................................</span></h2>
<div class="news">
	<?php foreach($news as $item) { ?>
		<p class="grey"><?php echo $objCommon->convertDate($item->created_date)?> года</p>
		<p class="black"><a href="<?php echo $objCommon->convertString($item->url) ?>" class="black"><?php echo $objCommon->convertString($item->page_description) ?>...</a><span class="blue">»</span></p>		
	<?php } ?>
	
	<div class="clearfix"></div>	
	<button class="green fleft" id="subscribe_btn">Подписаться</button>
	<button class="blue fright" onclick="location.href='<?php echo $config['news_all_url'] ?>';"><?php echo $config['news_button_label'] ?><span>+</span></button>
	<div class="clearfix"></div>
</div>

<div class="hr"></div>