<h2 class="green">Нас&nbsp;рекомендуют<span>............</span></h2>
<div class="recommendations">
	<?php echo $config['recommendations_text'] ?>	
	<div class="clearfix"></div>
	<button class="blue fright" onclick="location.href='<?php echo $config['recommendations_all_url'] ?>'"><?php echo $config['recommendations_button_label'] ?><span>+</span></button>
	<div class="clearfix"></div>
</div>

<div class="hr"></div>