<h2 class="green">Наши&nbsp;клиенты<span>...................</span></h2>
<div class="clients">
	<img src="../images/clients/clients_home.png" />
	<div class="clearfix"></div>
	<button class="blue fright" onclick="location.href='<?php echo $config['clients_all_url'] ?>'"><?php echo $config['client_button_label'] ?><span>+</span></button>
	<div class="clearfix"></div>
</div>

<div class="hr"></div>