<h2>Подписка&nbsp;на&nbsp;новости<span>...............</span></h2>
<div class="subscribe">
	<input type="text" id="email" name="email" placeholder="ваш e-mail" />
	
	<div class="unsubscribe_block">
		<div class="fleft">
			<input type="checkbox" id="unsubscribe" name="unsubscribe" />
		</div>
		<div class="fleft">
			<label for="unsubscribe">отказаться</label>
		</div>
		<button class="blue fright" id="unsubscribe_btn">Подписаться</button>
	</div>
	<div class="clearfix"></div>
</div>

<div class="hr"></div>