<div class="header_top_menu fright"><a href="/sitemap"><img src="../images/sitemap.png" alt="Карта сайта" title="Карта сайта"/></a></div>
<div class="header_top_menu fright"><img src="../images/info.png" alt="Контакты" title="Контакты"/><a href="/">Контакты</a></div>		  
<div class="header_top_menu fright"><img src="../images/about.png" alt="О компании" title="О компании"/><a href="/o-companii">О компании</a></div>
<div class="header_top_menu fright"><img src="../images/home.png" alt="Главная" title="Главная"/><a href="/">Главная</a></div>	