<button id="get_subscribers">Получить список адресов</button>
<p id="subscribers_list"></p>
<p>Чтобы получить список подписчиков на новости, необходимо отметить галочками нужные адреса и нажать "<b>Получить список адресов</b>".</p>
<p><span class="red">Красным цветом</span> отмечены отписаные от новостой адреса.</p>
<table class="emails">
	<thead>
		<th>&nbsp;</th>
		<th>#</th>
		<th>E-mail</th>
		<th>Дата</th>
		<th>Комментарий</th>
	</thead>
	<tbody id="emails_tbl"></tbody>
</table>