<div class="fright quick-links">
	<p><b>Быстрые ссылки</b></p>
	<div>
		<a class="quick_link" rel="1" href="#"><img src="images/add_page.png" /></a>&nbsp;&nbsp;<a class="quick_link" rel="1" href="#">Добавить статическую страницу</a>
	</div>
	<div>
		<a class="quick_link" rel="2" href="#"><img src="images/catalog_add.png" /></a>&nbsp;&nbsp;<a class="quick_link" rel="2" href="#">Добавить страницу каталога</a>
	</div>
	<div>
		<a class="quick_link" rel="3" href="#"><img src="images/news_add.png" /></a>&nbsp;&nbsp;<a class="quick_link" rel="3" href="#">Добавить новость</a>
	</div>
	<div>
		<a class="quick_link" rel="4" href="#"><img src="images/article_add.png" /></a>&nbsp;&nbsp;<a class="quick_link" rel="4" href="#">Добавить "К прочтению"</a>
	</div>
	<div>
		<a class="setup_visibility" href="#"><img src="images/settings_add.gif" /></a>&nbsp;&nbsp;<a class="setup_visibility" href="#">Видимость "Новостей" и "К прочтению"</a>
	</div>
</div>
<button id="new_page">Добавить страницу</button>
<p>Cтраницы сайта:</p>
<table class="pages">
	<thead>
		<th width="150">&nbsp;</th>
		<th width="50">#</th>
		<th width="300">Заголовок</th>
		<th width="200">URL</th>
		<th width="200">Категория:&nbsp;
			<select id="filter_page_category_id">
				<option value="-1">Показать все</option>
				<option value="0">Спрятанные</option>
				<option value="1" selected>Статические</option>
				<option value="2">Каталог</option>
				<option value="3">Новости</option>
				<option value="4">К прочтению</option>				
			</select>
		</th>
	</thead>
	<tbody id="pages_tbl"></tbody>
</table>
<div id="visibility-block" class="hidden"></div>
<div class="clearfix"></div>